# Generated by Django 5.0.1 on 2024-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedayauction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='onedayitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemid', models.IntegerField()),
                ('itemname', models.CharField(max_length=100)),
                ('itemdiscription', models.CharField(max_length=100)),
                ('itemstartingprice', models.IntegerField()),
                ('currentbidder', models.CharField(default='None', max_length=100)),
                ('currentbid', models.IntegerField(default=0)),
            ],
        ),
    ]
