# Generated by Django 5.0.1 on 2024-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedayauction', '0002_onedayitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onedayitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='onedayitem',
            name='itemid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
