# Generated by Django 5.0.1 on 2024-02-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedayauction', '0003_remove_onedayitem_id_alter_onedayitem_itemid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='onedayitem',
            new_name='auctionitem',
        ),
    ]
