# Generated by Django 5.0.1 on 2024-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedayauction', '0004_rename_onedayitem_auctionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='itemimage',
            field=models.ImageField(default='images/sitar.jpg', upload_to='images/'),
        ),
    ]
