# Generated by Django 5.0.1 on 2024-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedayauction', '0008_auctionitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='listdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
