# Generated by Django 5.0.1 on 2024-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedayauction', '0009_auctionitem_listdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
