# Generated by Django 5.0.1 on 2024-02-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedayauction', '0010_auctionitem_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidhistory',
            name='itemname',
        ),
    ]
