# Generated by Django 5.0.1 on 2024-02-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auctionobjects',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('itemid', models.IntegerField()),
            ],
        ),
    ]
