# Generated by Django 5.0.1 on 2024-02-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction24', '0002_alter_auctionobjects_objectid'),
        ('onedayauction', '0004_rename_onedayitem_auctionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionobjects',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onedayauction.auctionitem'),
        ),
    ]
