# Generated by Django 5.0.1 on 2024-02-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction24', '0003_alter_auctionobjects_itemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionobjects',
            old_name='objectid',
            new_name='slot',
        ),
    ]
